<h1>Numpy Assignment</h1>

<h2>Write the Code in empty cells to produce it's exact below output</h2>

<h3>Import Numpy</h3>

In [3]:
import numpy as np

<h3>Creating 3 Arrays (1-D, 2-D, 3-D)</h3>

In [6]:
array_1d = np.array([1,5,7,4])
array_1d

array([1, 5, 7, 4])

In [8]:
array_2d = np.array([[1, 2, 5],[4, 6, 9]])
array_2d

array([[1, 2, 5],
       [4, 6, 9]])

In [10]:
array_3d = np.array([[[ 1,  3,  5],
        [ 4,  9, 10],
        [ 5,  3,  2]],

       [[ 4,  6, 10],
        [ 5,  9,  8],
        [10,  3,  4]]])
array_3d

array([[[ 1,  3,  5],
        [ 4,  9, 10],
        [ 5,  3,  2]],

       [[ 4,  6, 10],
        [ 5,  9,  8],
        [10,  3,  4]]])

In [290]:
array_3d.ndim

3

<h3>Use attributes of Numpy (ndim, shape, size, dtype, itemsize) for all above 3 arrays</h3>

In [292]:
#dimensions of the arrays of 1D,2D,3D
arrar_1d.ndim,array_2d.ndim,array_3d.ndim

(1, 2, 3)

In [293]:
#Shape of the arrays
arrar_1d.shape,array_2d.shape,array_3d.shape

((4,), (2, 3), (2, 3, 3))

In [294]:
#Size of the array
arrar_1d.size,array_2d.shape,array_3d.shape

(4, (2, 3), (2, 3, 3))

In [295]:
#dtype of array
arrar_1d.dtype,array_2d.dtype,array_3d.dtype

(dtype('int32'), dtype('int32'), dtype('int32'))

In [296]:
#itemsize of the arrays
arrar_1d.itemsize,array_2d.itemsize,array_3d.itemsize

(4, 4, 4)

<h3>Create Range Arrays</h3>

In [298]:
# This matrix (5x5) will have elements within the range of 0-99 with step size of 4
matrix = np.arange(0,100,4)
matrix

array([ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36, 40, 44, 48, 52, 56, 60, 64,
       68, 72, 76, 80, 84, 88, 92, 96])

In [299]:
#matrix afterthe reshaping
matrix.reshape(5,5)

array([[ 0,  4,  8, 12, 16],
       [20, 24, 28, 32, 36],
       [40, 44, 48, 52, 56],
       [60, 64, 68, 72, 76],
       [80, 84, 88, 92, 96]])

<h3>Creating a Random array within range of 0-50</h3>

In [301]:
# This Matrix (4x6) will have random integers within range 0-50
matrix_1 = np.random.randint(0,51, size = (4,6))
matrix_1

array([[26, 38, 10, 49, 31, 40],
       [ 7, 34,  7, 44, 13,  3],
       [42, 15, 34, 16, 25, 19],
       [ 9, 12, 46,  4, 48,  2]])

<h3>Creating a Random array within range of 0.0 and 1.0 (Float)</h3>

In [12]:
#This 3x4 Matrix will have the float range from 0.0 to 1.0
matrix_2 = np.random.rand(2,3)
matrix_2

array([[0.02292909, 0.69882496, 0.96049191],
       [0.32466143, 0.86080383, 0.2085888 ]])

In [304]:
matrix_2.dtype,matrix_2.shape,matrix_2.ndim

(dtype('float64'), (3, 4), 2)

<h3>Array Indexing</h3>

In [14]:
# Create the array
new_arr_1 = np.array([[15, 42, 41, 38, 49,  3],
       [13,  8, 25, 25, 48,  5],
       [34, 22, 12, 37, 26, 48],
       [31, 30, 46, 40,  5, 40]])
new_arr_1

array([[15, 42, 41, 38, 49,  3],
       [13,  8, 25, 25, 48,  5],
       [34, 22, 12, 37, 26, 48],
       [31, 30, 46, 40,  5, 40]])

In [16]:
# Return Unique Elements in the array
np.unique(new_arr_1)

array([ 3,  5,  8, 12, 13, 15, 22, 25, 26, 30, 31, 34, 37, 38, 40, 41, 42,
       46, 48, 49])

In [20]:
#Return the second and third row elements
print(f"First row elements are :",new_arr_1[0])

First row elements are : [15 42 41 38 49  3]


In [22]:
# Return 3rd Row 3rd Element (Indexing starts with 0)
new_arr_1[2,2]

12

In [24]:
# Return 1rd Row 4rd Element (Indexing starts with 0)
new_arr_1[0,3]

38

In [26]:
# Create the follwoing array
arr = np.array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]]])
arr

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]]])

In [28]:
arr[0]

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [32]:
arr[0,1,2]

5

<h3>Array Slicing</h3>

<h3>Slicing 1-Dimensional Arrays</h3>

In [36]:
array_1d

array([1, 5, 7, 4])

In [38]:
array_1d[2:]

array([7, 4])

<h3>Slicing 2-Dimensional Arrays</h3>

In [64]:
arr2ds = np.array([[15, 42, 41, 38, 49,  3],
       [13,  8, 25, 25, 48,  5],
       [34, 22, 12, 37, 26, 48],
       [31, 30, 46, 40,  5, 40]])
arr2ds

array([[15, 42, 41, 38, 49,  3],
       [13,  8, 25, 25, 48,  5],
       [34, 22, 12, 37, 26, 48],
       [31, 30, 46, 40,  5, 40]])

In [66]:
arr2ds[:,1:3]

array([[42, 41],
       [ 8, 25],
       [22, 12],
       [30, 46]])

In [68]:
arr2ds[0:3,0:3]

array([[15, 42, 41],
       [13,  8, 25],
       [34, 22, 12]])

In [70]:
# Produce the following result
arr2ds[1:3,3:5]

array([[25, 48],
       [37, 26]])

<h3>Assigning Values to Arrays (Broadcasting)</h3>

<h3>1-Dimensional Arrays Broadcasting</h3>


In [74]:
#creating the 1-D array
array_1d

array([  1, 888, 888, 888])

In [76]:
# Change Index 3 value to 88
array_1d[3] = 99
array_1d

array([  1, 888, 888,  99])

In [78]:
# Change the Index vales by slicing
array_1d[1:] = 888
array_1d

array([  1, 888, 888, 888])

<h3>2-Dimensional Arrays Broadcasting</h3>

In [81]:
# Create the 2-D Array
array_2d

array([[  1, 777, 777],
       [  4,   6,   9]])

In [83]:
array_2d[0,1] = 100
array_2d

array([[  1, 100, 777],
       [  4,   6,   9]])

In [85]:
# Change values by slicing the matrix and produce the follwoing results
array_2d[0, 1:] =777
array_2d

array([[  1, 777, 777],
       [  4,   6,   9]])

<h2>Numpy Operations</h2>

<h3>Arithmetic Operations</h3>

In [89]:
arr2ds

array([[15, 42, 41, 38, 49,  3],
       [13,  8, 25, 25, 48,  5],
       [34, 22, 12, 37, 26, 48],
       [31, 30, 46, 40,  5, 40]])

In [98]:
#Add  +20 to each element
arr2ds + 10

array([[25, 52, 51, 48, 59, 13],
       [23, 18, 35, 35, 58, 15],
       [44, 32, 22, 47, 36, 58],
       [41, 40, 56, 50, 15, 50]])

In [100]:
#Add  -5 to each element
arr2ds - 10

array([[ 5, 32, 31, 28, 39, -7],
       [ 3, -2, 15, 15, 38, -5],
       [24, 12,  2, 27, 16, 38],
       [21, 20, 36, 30, -5, 30]])

In [102]:
# Multiplying each element with 5
new_arr_1 * 9

array([[135, 378, 369, 342, 441,  27],
       [117,  72, 225, 225, 432,  45],
       [306, 198, 108, 333, 234, 432],
       [279, 270, 414, 360,  45, 360]])

In [104]:
# Dividing each element with 2
arr2ds / 2

array([[ 7.5, 21. , 20.5, 19. , 24.5,  1.5],
       [ 6.5,  4. , 12.5, 12.5, 24. ,  2.5],
       [17. , 11. ,  6. , 18.5, 13. , 24. ],
       [15.5, 15. , 23. , 20. ,  2.5, 20. ]])

<h2>Statistical Operations</h2>

In [110]:
new_arr_2 = np.array([[2,3,4],
                      [4,3,17],
                      [89,33,12]])
new_arr_2

array([[ 2,  3,  4],
       [ 4,  3, 17],
       [89, 33, 12]])

In [112]:
#sum operator
total_sum = new_arr_2.sum()
total_sum

167

In [114]:
#sum of 1 row
row1_sum = new_arr_2.sum(axis = 1)
row1_sum

array([  9,  24, 134])

In [116]:
col_sum = new_arr_2.sum(1)
col_sum

array([  9,  24, 134])

In [118]:
# Calculate Mean, Meadian, Square root, minimum, maximum values of new_arr
new_arr_2

array([[ 2,  3,  4],
       [ 4,  3, 17],
       [89, 33, 12]])

In [120]:
# Calculating Mean of array
mean= np.mean(new_arr_2)
mean

18.555555555555557

In [122]:
# Calculating Median of array
median= np.median(new_arr_2)
median

4.0

In [124]:
# Calculating square root of array
square_root = np.sqrt(new_arr_2)
square_root

array([[1.41421356, 1.73205081, 2.        ],
       [2.        , 1.73205081, 4.12310563],
       [9.43398113, 5.74456265, 3.46410162]])

In [126]:
# finding the minimum element  of the array
minimum = np.min(new_arr_2)
minimum

2

In [128]:
# finding the maximum element  of the array
maximum = np.max(new_arr_2)
maximum

89